# Monitoring Configuration

TOPIC_NAME=LambdaMonitoringReports
LOGGING_POLICY_NAME=logging
MONITOR_POLICY_NAME=lambda-monitoring
MONITOR_ROLE_NAME=lambda-monitoring
MONITOR_FUNCTION_NAME=monitor-lambda-runs

APP_FUNCTION_NAME=marchon-map-geojson
APP_ROLE_NAME=marchon-lambda-role
APP_SUBSCRIPTION_EMAIL=d6d7b5b3u0m8u8c0@ragtag-team.slack.com